/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/_dashboard'
import { Route as ProtectedDashboardDashboardRouteImport } from './routes/_protected/_dashboard/dashboard'
import { Route as ProtectedDashboardUserUsernamePostsRouteImport } from './routes/_protected/_dashboard/_user/$username/posts'
import { Route as ProtectedDashboardUserUsernameCommentsRouteImport } from './routes/_protected/_dashboard/_user/$username/comments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardDashboardRoute =
  ProtectedDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardUserUsernamePostsRoute =
  ProtectedDashboardUserUsernamePostsRouteImport.update({
    id: '/_user/$username/posts',
    path: '/$username/posts',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardUserUsernameCommentsRoute =
  ProtectedDashboardUserUsernameCommentsRouteImport.update({
    id: '/_user/$username/comments',
    path: '/$username/comments',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardDashboardRoute
  '/$username/comments': typeof ProtectedDashboardUserUsernameCommentsRoute
  '/$username/posts': typeof ProtectedDashboardUserUsernamePostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardDashboardRoute
  '/$username/comments': typeof ProtectedDashboardUserUsernameCommentsRoute
  '/$username/posts': typeof ProtectedDashboardUserUsernamePostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/_dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/_dashboard/dashboard': typeof ProtectedDashboardDashboardRoute
  '/_protected/_dashboard/_user/$username/comments': typeof ProtectedDashboardUserUsernameCommentsRoute
  '/_protected/_dashboard/_user/$username/posts': typeof ProtectedDashboardUserUsernamePostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/$username/comments'
    | '/$username/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/$username/comments'
    | '/$username/posts'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/faq'
    | '/login'
    | '/signup'
    | '/_protected/_dashboard'
    | '/_protected/_dashboard/dashboard'
    | '/_protected/_dashboard/_user/$username/comments'
    | '/_protected/_dashboard/_user/$username/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_dashboard': {
      id: '/_protected/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_dashboard/dashboard': {
      id: '/_protected/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardDashboardRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/_user/$username/posts': {
      id: '/_protected/_dashboard/_user/$username/posts'
      path: '/$username/posts'
      fullPath: '/$username/posts'
      preLoaderRoute: typeof ProtectedDashboardUserUsernamePostsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/_dashboard/_user/$username/comments': {
      id: '/_protected/_dashboard/_user/$username/comments'
      path: '/$username/comments'
      fullPath: '/$username/comments'
      preLoaderRoute: typeof ProtectedDashboardUserUsernameCommentsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardDashboardRoute: typeof ProtectedDashboardDashboardRoute
  ProtectedDashboardUserUsernameCommentsRoute: typeof ProtectedDashboardUserUsernameCommentsRoute
  ProtectedDashboardUserUsernamePostsRoute: typeof ProtectedDashboardUserUsernamePostsRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardDashboardRoute: ProtectedDashboardDashboardRoute,
  ProtectedDashboardUserUsernameCommentsRoute:
    ProtectedDashboardUserUsernameCommentsRoute,
  ProtectedDashboardUserUsernamePostsRoute:
    ProtectedDashboardUserUsernamePostsRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
